version: '3'

# networks
networks:
  # internal network
  internal:
    driver: bridge

# volumes
volumes:
  # MySQL data volume
  samurai-mysql_data:
    driver: local

# services
services:

  # database
  samurai-mysql:
    image: mysql:5.7
    container_name: samurai-mysql
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - samurai-mysql_data:/var/lib/mysql
      - .:/var/www/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  # api
  samurai-nginx:
    image: webdevops/php-nginx-dev:8.0
    container_name: samurai-nginx
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    depends_on:
      - samurai-mysql
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - PHP_DEBUGGER="xdebug"
      #      - PHP_IDE_CONFIG="serverName=_"
      - XDEBUG_REMOTE_AUTOSTART=On
      - XDEBUG_REMOTE_CONNECT_BACK=Off
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - XDEBUG_REMOTE_PORT=9090
      - XDEBUG_PROFILER_ENABLE=Off
      - PHP_DATE_TIMEZONE=UTC
      - PHP_DISPLAY_ERRORS=0
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
    expose:
      - 9090
    ports:
      - 8080:80
